### ISSUE TITLE
Packets not recognized by Wireshark

### ISSUE THREAD

**Issue by amitgeron** [NTAP/quant#46]
All traffic between client and server is interpreted as normal UDP.
Forcing Wireshark to decode the packets as QUIC, results in various errors.
E.g.:
```
> Expert Info (Note/Protocol): Unknown QUIC connection. Missing Initial Packet or migrated connection?
> Expert Info (Warning/Decryption): Failed to create decryption context: Decryption (checktag) failed: Checksum error
> Expert Info (Warning/Decryption): Failed to create decryption context: Unable to retrieve cipher information
> Expert Info (Warning/Decryption): Failed to decrypt packet number
```

**Comment by larseggert** [comment]
Are you on the latest master version? Are you using the most recent wireshark nightly? Are you feeding the TLS log into wireshark (default location `/tmp/quant-tlslog`)?

**Comment by amitgeron** [comment]
Versions:
QUANT - ccf9ecdda548dbd6cdb2b775bc725eb929e8d0da (with submodules up-to-date)
Wireshark - Version 3.0.2 (Git commit 621ed351d5c9)
TLS log set correctly. Please note that in case TLS log is absent, Wireshark would still able to recognize QUIC packets.

**Comment by larseggert** [comment]
Maybe try and go back to 9afd82236897dde61535c150a1a1ad23191a5205? I can't look into this much for the next two weeks, sorry

**Comment by larseggert** [comment]
Also, please try a newer wireshark - the 3.1.0 series is the current nightly: https://www.wireshark.org/download/automated/osx/

**Comment by adikabintang** [comment]
@amitgeron You may want to use Wireshark version commit `5e79558a8243c046ce3f279c635f9670be7f8f05` or newer. 

You can either `git clone https://code.wireshark.org/review/wireshark` or download from here https://www.wireshark.org/download/automated/src/

**Comment by amitgeron** [comment]
Same result with 3.1.0rc0-1058-g142e024e1f02 (Git commit 6183dc441c38)

I don't think this is a wireshark issue, since with other implementations of QUIC I don't experience this issue.

**Comment by larseggert** [comment]
Would you try going back to the commit before I shortened the exporter labels? I just made that change due to what @lekensteyn

**Comment by larseggert** [comment]
Wrote in #12 but didn’t test it fully

**Comment by amitgeron** [comment]
Tested with commit 9afd82236897dde61535c150a1a1ad23191a5205, and after forcing Wireshark to decode the packets as QUIC, I get no errors.

**Comment by larseggert** [comment]
Thanks for confirming this. I guess it’s an issue with the shortened labels then, either in quant or in wireshark (cc @lekensteyn @alaguette)

**Comment by larseggert** [comment]
Hang on, the commit you refer to doesn’t even change the TLS exporter code. Did you `hit bisect` this, or just pick some precious version?

**Comment by Lekensteyn** [comment]
Key logging works for me.
```
sudo tcpdump -i lo -p -w quant.pcap &
bin/server &
bin/client http://localhost:4433 -l quant.keys
editcap --inject-secrets tls,quant.keys quant.pcap quant-dsb.pcapng
wireshark -r quant-dsb.pcapng -dudp.port==4433,quic
```
Capture file with embedded keys (ZIP due to Github limitations): [quant-dsb.pcapng.zip](https://github.com/NTAP/quant/files/3315872/quant-dsb.pcapng.zip)

With Wireshark v3.1.0rc0-1099-g2d96da9b7f (git master), everything can be decrypted, except for 0-RTT data (need to check why).

The version field is reported as "0x45474714" instead of the official draft version 0xff000014 (draft-20). That is likely the reason why Wireshark heuristics refuses to interpret it, requiring a manual Decode As action.

quant was built on Arch Linux with:
```
sudo pacman -S git cmake ninja libbsd http-parser libev
git clone --depth=100 https://github.com/NTAP/quant /tmp/quant
mkdir /tmp/build && cd /tmp/build
cmake -GNinja /tmp/quant -DCMAKE_BUILD_TYPE=Debug
ninja
```

Environment:
- gcc 9.1.0-1
- http-parser 2.9.2-1
- openssl 1.1.1.c-1
- libev 4.25-1
- cmake 3.14.5-1
- Sources:
  - NTAP/quant@e6082f6ac8
  - attractivechaos/klib@f719aad5fa
  - NTAP/warpcore@184cc0458f
  - h2o/picotest@f390562fd4
  - h2o/picotls@27f31ba0a8
  - private-octopus/picoquic@9d43127b33
  - https://git.lighttpd.net/libev 31ca40b7a1
  - attractivechaos/klib@f719aad5fa

If you still run into problems, can you share a pcapng file with embedded secrets as described above? A separate pcap + key log file would also work.

**Comment by amitgeron** [comment]
Thanks!
I can confirm that all looks good now. I built latest Wireshark, which already includes the patch that you mentioned.

**Comment by larseggert** [comment]
Thanks all for confirming things; I’m closing this now

**Comment by Lekensteyn** [comment]
@larseggert you actually reopened it :smile:

**Comment by larseggert** [comment]
Man this CodeHub app is not great
